# Generated by Django 2.2.3 on 2019-12-26 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('sqft', models.FloatField(default=0)),
                ('beds', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('family_type', models.CharField(blank=True, max_length=100)),
                ('year_built', models.IntegerField(default=2020)),
                ('heating', models.CharField(blank=True, max_length=100)),
                ('cooling', models.CharField(blank=True, max_length=100)),
                ('parking', models.IntegerField(default=0)),
                ('lot', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('image1', models.ImageField(blank=True, upload_to='')),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('image3', models.ImageField(blank=True, upload_to='')),
                ('image4', models.ImageField(blank=True, upload_to='')),
                ('image5', models.ImageField(blank=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tourrequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(blank=True)),
                ('time1_date1', models.TimeField(blank=True)),
                ('time2_date1', models.TimeField(blank=True)),
                ('time3_date1', models.TimeField(blank=True)),
                ('date2', models.DateField(blank=True)),
                ('time1_date2', models.TimeField(blank=True)),
                ('time2_date2', models.TimeField(blank=True)),
                ('time3_date2', models.TimeField(blank=True)),
                ('date3', models.DateField(blank=True)),
                ('time1_date3', models.TimeField(blank=True)),
                ('time2_date3', models.TimeField(blank=True)),
                ('time3_date3', models.TimeField(blank=True)),
                ('relproperty', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='relpropertytr', to='functionality.properties')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='shortlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('relproperties', models.ManyToManyField(blank=True, to='functionality.properties')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('reciever', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL)),
                ('relproperty', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='relproperty', to='functionality.properties')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
