# Generated by Django 2.2.3 on 2019-12-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourrequests',
            name='date1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tourrequests',
            name='date2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tourrequests',
            name='date3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tourrequests',
            name='time1_date1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tourrequests',
            name='time1_date2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tourrequests',
            name='time1_date3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tourrequests',
            name='time2_date1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tourrequests',
            name='time2_date2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tourrequests',
            name='time2_date3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tourrequests',
            name='time3_date1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tourrequests',
            name='time3_date2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tourrequests',
            name='time3_date3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
