# Generated by Django 2.2.3 on 2020-01-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0003_auto_20200125_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
