# Generated by Django 2.2.3 on 2020-02-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0004_properties_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrequests',
            name='note',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.RemoveField(
            model_name='tourrequests',
            name='relproperty',
        ),
        migrations.AddField(
            model_name='tourrequests',
            name='relproperty',
            field=models.ManyToManyField(blank=True, related_name='relpropertytr', to='functionality.properties'),
        ),
    ]
