# Generated by Django 2.2.3 on 2020-02-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0006_tourrequests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrequests',
            name='name',
            field=models.CharField(default='Tour Name', max_length=50),
        ),
    ]
