# Generated by Django 2.2.3 on 2020-02-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0009_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notereply',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='tourrequests',
            name='status',
            field=models.CharField(blank=True, choices=[('In Creation', 'In Creation'), ('In Process', 'In Process'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='In Creation', max_length=20),
        ),
    ]
