# Generated by Django 2.2.3 on 2020-02-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0010_auto_20200213_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='notereply',
        ),
    ]
