# Generated by Django 2.2.3 on 2020-02-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0011_remove_notes_notereply'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
