# Generated by Django 2.2.3 on 2020-02-14 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('functionality', '0012_offers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_with', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offers',
            name='status',
            field=models.CharField(default='Submitted', max_length=50),
        ),
    ]
