# Generated by Django 2.2.3 on 2020-02-14 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('functionality', '0013_auto_20200214_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='linked_with',
            field=models.ManyToManyField(blank=True, related_name='linked_with', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourrequests',
            name='status',
            field=models.CharField(blank=True, choices=[('In Creation', 'In Creation'), ('Requested', 'Requested'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='In Creation', max_length=20),
        ),
    ]
