# Generated by Django 2.2.3 on 2020-02-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0014_auto_20200215_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='propertyrating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('linklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functionality.shortlist')),
                ('relproperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functionality.properties')),
            ],
        ),
    ]
