# Generated by Django 2.2.7 on 2020-02-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0015_propertyrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourrequests',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
