# Generated by Django 2.2.3 on 2019-12-26 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNumber', models.BigIntegerField(blank=True, null=True)),
                ('approve', models.BooleanField(default=True)),
                ('Teacher_or_Parent', models.CharField(blank=True, choices=[('Buyer', 'Buyer'), ('Agent', 'Agent')], default='Buyer', max_length=10)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('Price_Range', models.CharField(blank=True, max_length=200, null=True)),
                ('has_pre_approval', models.CharField(blank=True, max_length=200, null=True)),
                ('property_type', models.CharField(blank=True, max_length=200, null=True)),
                ('beds', models.CharField(blank=True, max_length=200, null=True)),
                ('bath', models.CharField(blank=True, max_length=200, null=True)),
                ('lot_size', models.CharField(blank=True, max_length=200, null=True)),
                ('stories', models.CharField(blank=True, max_length=200, null=True)),
                ('location_preference', models.CharField(blank=True, max_length=200, null=True)),
                ('looking_to_buy_in_how_many_months', models.CharField(blank=True, max_length=200, null=True)),
                ('How_long_have_you_been_house_hunting', models.CharField(blank=True, max_length=200, null=True)),
                ('Life_style', models.CharField(blank=True, choices=[('Short Commute to work', 'Short Commute to work'), ('Access to shopping', 'Access to shopping'), ('Vastu Preference', 'Vastu Preference'), ('School Requirements', 'School Requirements')], max_length=200, null=True)),
                ('any_other', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
