# Generated by Django 2.2.3 on 2020-02-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_profilemodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='Price_Range',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='lot_size',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='maxlot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='maxprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='maxsqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='minlot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='minprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='minsqft',
            field=models.IntegerField(default=0),
        ),
    ]
