# Generated by Django 2.2.7 on 2020-02-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_remove_profilemodel_contactnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='occupation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
