# Generated by Django 2.2.7 on 2020-02-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200215_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
    ]
